spring.application.name=socialease-backend

# Server
server.port=8080
server.servlet.context-path=/api/v1

# Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/socialease
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=my-secret-key-for-jwt-token-generation-and-validation-ensure-minimum-256-bits
jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.level.com.SAH.backend=DEBUG

# Disable Docker Compose (use system PostgreSQL)
spring.docker.compose.enabled=false
